import type { Metadata } from "next";
import NavBar from "@/components/Navbar";
import QueryClientProv from "@/components/QueryClientProv";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='grid grid-cols-5'>
          <NavBar />
          <div className="col-span-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}


